### ISSUE TITLE
Do you any algorithm in Scala?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/scala#1]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Scala](https://github.com/AllAlgorithms/scala) this case

**Comment by ashu2012** [comment]
floodfill algorithm , i can add . It is used in maze solving  and paint programs.
